---
version: '2'
services:

  connect:
    image: localbuild/connect_custom_example:latest
    hostname: connect
    container_name: connect
    ports:
      "8083:8083"
    environment:
      # STANDALONE_ properties are for the Connect worker
      STANDALONE_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
      STANDALONE_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      STANDALONE_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      STANDALONE_OFFSET_STORAGE_FILE_FILENAME: /tmp/connect.offsets
      STANDALONE_OFFSET_FLUSH_INTERVAL_MS: 10000
      STANDALONE_SSL.ENDPOINT.IDENTIFICATION.ALGORITHM: https
      STANDALONE_SECURITY_PROTOCOL: SASL_SSL
      STANDALONE_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      STANDALONE_SASL_MECHANISM: PLAIN
      STANDALONE_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      STANDALONE_PRODUCER_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      STANDALONE_PRODUCER_SASL_MECHANISM: PLAIN
      STANDALONE_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      STANDALONE_CONSUMER_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      STANDALONE_CONSUMER_SASL_MECHANISM: PLAIN
      STANDALONE_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
      STANDALONE_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
      STANDALONE_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      STANDALONE_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: $SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
      STANDALONE_KEY_CONVERTER_SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
      STANDALONE_KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      STANDALONE_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: $SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
      STANDALONE_KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      STANDALONE_REST_PORT: 8083

      # CONNECT_ properties are for the connector itself, example shown below
      CONNECT_NAME: elasticsearch-sink-connector
      CONNECT_CONNECTOR_CLASS: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
      CONNECT_TYPE_NAME: _doc
      CONNECT_TOPICS: test01
      CONNECT_KEY_IGNORE: true
      CONNECT_SCHEMA_IGNORE: false
      CONNECT_CONNECTION_URL: http://elasticsearch:9200
